"""Initial project setup again

Revision ID: 1a98c217284a
Revises: 
Create Date: 2025-05-29 23:01:16.774932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a98c217284a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chauffeur',
    sa.Column('id_chauffeur', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('numero_telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('categorie_ch', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_chauffeur'),
    sa.UniqueConstraint('email')
    )
    op.create_table('client_initial',
    sa.Column('id_client_initial', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('numero_telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id_client_initial'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sous_traitant',
    sa.Column('id_sous_traitant', sa.Integer(), nullable=False),
    sa.Column('nom_entreprise', sa.String(length=255), nullable=False),
    sa.Column('contact_personne', sa.String(length=100), nullable=True),
    sa.Column('numero_telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_sous_traitant'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nom_entreprise')
    )
    op.create_table('type_indispo_chauffeur',
    sa.Column('id_type_indispo_chauffeur', sa.Integer(), nullable=False),
    sa.Column('nom_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_type_indispo_chauffeur'),
    sa.UniqueConstraint('nom_type')
    )
    op.create_table('type_indispo_vehicule',
    sa.Column('id_type_indispo_vehicule', sa.Integer(), nullable=False),
    sa.Column('nom_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_type_indispo_vehicule'),
    sa.UniqueConstraint('nom_type')
    )
    op.create_table('type_vehicule',
    sa.Column('id_type_vehicule', sa.Integer(), nullable=False),
    sa.Column('nom_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_type_vehicule'),
    sa.UniqueConstraint('nom_type')
    )
    op.create_table('vehicule',
    sa.Column('id_vehicule', sa.Integer(), nullable=False),
    sa.Column('immatriculation_ve', sa.String(length=50), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_vehicule'),
    sa.UniqueConstraint('immatriculation_ve')
    )
    op.create_table('ville',
    sa.Column('id_ville', sa.Integer(), nullable=False),
    sa.Column('code_ville', sa.String(length=50), nullable=False),
    sa.Column('nom_ville', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_ville'),
    sa.UniqueConstraint('code_ville')
    )
    op.create_table('chauffeur_externe',
    sa.Column('id_chauffeur_externe', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('numero_telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('categorie_permis', sa.String(length=50), nullable=True),
    sa.Column('id_sous_traitant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_sous_traitant'], ['sous_traitant.id_sous_traitant'], ),
    sa.PrimaryKeyConstraint('id_chauffeur_externe'),
    sa.UniqueConstraint('email')
    )
    op.create_table('client_final',
    sa.Column('id_client_final', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('numero_telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('id_client_initial', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_client_initial'], ['client_initial.id_client_initial'], ),
    sa.PrimaryKeyConstraint('id_client_final')
    )
    op.create_table('date_cv',
    sa.Column('id_date_cv', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id_chauffeur', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_chauffeur'], ['chauffeur.id_chauffeur'], ),
    sa.PrimaryKeyConstraint('id_date_cv')
    )
    op.create_table('date_tr',
    sa.Column('id_date_tr', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id_vehicule', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_vehicule'], ['vehicule.id_vehicule'], ),
    sa.PrimaryKeyConstraint('id_date_tr')
    )
    op.create_table('feuille_de_route',
    sa.Column('id_feuille_de_route', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('date_depart_prevu', sa.Date(), nullable=False),
    sa.Column('heure_depart_prevu', sa.Time(), nullable=False),
    sa.Column('date_arrivee_prevue', sa.Date(), nullable=False),
    sa.Column('heure_arrivee_prevue', sa.Time(), nullable=False),
    sa.Column('date_depart_reel', sa.Date(), nullable=True),
    sa.Column('heure_depart_reel', sa.Time(), nullable=True),
    sa.Column('date_arrivee_reelle', sa.Date(), nullable=True),
    sa.Column('heure_arrivee_reelle', sa.Time(), nullable=True),
    sa.Column('km_debut', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('km_fin', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id_chauffeur', sa.Integer(), nullable=False),
    sa.Column('id_vehicule', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_chauffeur'], ['chauffeur.id_chauffeur'], ),
    sa.ForeignKeyConstraint(['id_vehicule'], ['vehicule.id_vehicule'], ),
    sa.PrimaryKeyConstraint('id_feuille_de_route')
    )
    op.create_table('indisponibilite_chauffeur',
    sa.Column('id_indispo_chauffeur', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id_chauffeur', sa.Integer(), nullable=False),
    sa.Column('id_type_indispo_chauffeur', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_chauffeur'], ['chauffeur.id_chauffeur'], ),
    sa.ForeignKeyConstraint(['id_type_indispo_chauffeur'], ['type_indispo_chauffeur.id_type_indispo_chauffeur'], ),
    sa.PrimaryKeyConstraint('id_indispo_chauffeur')
    )
    op.create_table('indisponibilite_vehicule',
    sa.Column('id_indispo_vehicule', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id_vehicule', sa.Integer(), nullable=False),
    sa.Column('id_type_indispo_vehicule', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_type_indispo_vehicule'], ['type_indispo_vehicule.id_type_indispo_vehicule'], ),
    sa.ForeignKeyConstraint(['id_vehicule'], ['vehicule.id_vehicule'], ),
    sa.PrimaryKeyConstraint('id_indispo_vehicule')
    )
    op.create_table('localisation',
    sa.Column('id_localisation', sa.Integer(), nullable=False),
    sa.Column('id_chauffeur', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_chauffeur'], ['chauffeur.id_chauffeur'], ),
    sa.PrimaryKeyConstraint('id_localisation')
    )
    op.create_table('province',
    sa.Column('id_province', sa.Integer(), nullable=False),
    sa.Column('nom_province', sa.String(length=100), nullable=False),
    sa.Column('id_ville', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ville'], ['ville.id_ville'], ),
    sa.PrimaryKeyConstraint('id_province')
    )
    op.create_table('service_client',
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('nom_service', sa.String(length=100), nullable=False),
    sa.Column('id_client_initial', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_client_initial'], ['client_initial.id_client_initial'], ),
    sa.PrimaryKeyConstraint('id_service')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('id_client_initial', sa.Integer(), nullable=True),
    sa.Column('id_chauffeur', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_chauffeur'], ['chauffeur.id_chauffeur'], ),
    sa.ForeignKeyConstraint(['id_client_initial'], ['client_initial.id_client_initial'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('vehicule_externe',
    sa.Column('id_vehicule_externe', sa.Integer(), nullable=False),
    sa.Column('immatriculation_ve', sa.String(length=50), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id_sous_traitant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_sous_traitant'], ['sous_traitant.id_sous_traitant'], ),
    sa.PrimaryKeyConstraint('id_vehicule_externe'),
    sa.UniqueConstraint('immatriculation_ve')
    )
    op.create_table('destination',
    sa.Column('id_destination', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id_ville', sa.Integer(), nullable=True),
    sa.Column('id_province', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_province'], ['province.id_province'], ),
    sa.ForeignKeyConstraint(['id_ville'], ['ville.id_ville'], ),
    sa.PrimaryKeyConstraint('id_destination')
    )
    op.create_table('entete_commande',
    sa.Column('id_entete_commande', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('date_commande', sa.Date(), nullable=False),
    sa.Column('id_client_initial', sa.Integer(), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_client_initial'], ['client_initial.id_client_initial'], ),
    sa.ForeignKeyConstraint(['id_service'], ['service_client.id_service'], ),
    sa.PrimaryKeyConstraint('id_entete_commande'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('detail_commande',
    sa.Column('id_detail_commande', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('description_colis', sa.String(length=255), nullable=True),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('poids', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id_entete_commande', sa.Integer(), nullable=False),
    sa.Column('id_type_vehicule', sa.Integer(), nullable=False),
    sa.Column('id_client_final', sa.Integer(), nullable=False),
    sa.Column('id_destination', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_client_final'], ['client_final.id_client_final'], ),
    sa.ForeignKeyConstraint(['id_destination'], ['destination.id_destination'], ),
    sa.ForeignKeyConstraint(['id_entete_commande'], ['entete_commande.id_entete_commande'], ),
    sa.ForeignKeyConstraint(['id_type_vehicule'], ['type_vehicule.id_type_vehicule'], ),
    sa.PrimaryKeyConstraint('id_detail_commande')
    )
    op.create_table('mission',
    sa.Column('id_mission', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('id_chauffeur', sa.Integer(), nullable=False),
    sa.Column('id_vehicule', sa.Integer(), nullable=False),
    sa.Column('id_destination', sa.Integer(), nullable=True),
    sa.Column('id_feuille_de_route', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_chauffeur'], ['chauffeur.id_chauffeur'], ),
    sa.ForeignKeyConstraint(['id_destination'], ['destination.id_destination'], ),
    sa.ForeignKeyConstraint(['id_feuille_de_route'], ['feuille_de_route.id_feuille_de_route'], ),
    sa.ForeignKeyConstraint(['id_vehicule'], ['vehicule.id_vehicule'], ),
    sa.PrimaryKeyConstraint('id_mission')
    )
    op.create_table('trajet',
    sa.Column('id_trajet', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('duree_heures', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id_destination', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_destination'], ['destination.id_destination'], ),
    sa.PrimaryKeyConstraint('id_trajet')
    )
    op.create_table('affretement',
    sa.Column('id_affretement', sa.Integer(), nullable=False),
    sa.Column('date_demande', sa.Date(), nullable=False),
    sa.Column('date_debut_souhaitee', sa.Date(), nullable=False),
    sa.Column('date_fin_souhaitee', sa.Date(), nullable=False),
    sa.Column('description_besoin', sa.String(length=500), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('cout_estime', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id_detail_commande', sa.Integer(), nullable=True),
    sa.Column('id_sous_traitant', sa.Integer(), nullable=True),
    sa.Column('id_vehicule_externe', sa.Integer(), nullable=True),
    sa.Column('id_chauffeur_externe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_chauffeur_externe'], ['chauffeur_externe.id_chauffeur_externe'], ),
    sa.ForeignKeyConstraint(['id_detail_commande'], ['detail_commande.id_detail_commande'], ),
    sa.ForeignKeyConstraint(['id_sous_traitant'], ['sous_traitant.id_sous_traitant'], ),
    sa.ForeignKeyConstraint(['id_vehicule_externe'], ['vehicule_externe.id_vehicule_externe'], ),
    sa.PrimaryKeyConstraint('id_affretement')
    )
    op.create_table('mission_detail',
    sa.Column('id_mission', sa.Integer(), nullable=False),
    sa.Column('id_detail_commande', sa.Integer(), nullable=False),
    sa.Column('ordre_livraison', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_detail_commande'], ['detail_commande.id_detail_commande'], ),
    sa.ForeignKeyConstraint(['id_mission'], ['mission.id_mission'], ),
    sa.PrimaryKeyConstraint('id_mission', 'id_detail_commande')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mission_detail')
    op.drop_table('affretement')
    op.drop_table('trajet')
    op.drop_table('mission')
    op.drop_table('detail_commande')
    op.drop_table('entete_commande')
    op.drop_table('destination')
    op.drop_table('vehicule_externe')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('service_client')
    op.drop_table('province')
    op.drop_table('localisation')
    op.drop_table('indisponibilite_vehicule')
    op.drop_table('indisponibilite_chauffeur')
    op.drop_table('feuille_de_route')
    op.drop_table('date_tr')
    op.drop_table('date_cv')
    op.drop_table('client_final')
    op.drop_table('chauffeur_externe')
    op.drop_table('ville')
    op.drop_table('vehicule')
    op.drop_table('type_vehicule')
    op.drop_table('type_indispo_vehicule')
    op.drop_table('type_indispo_chauffeur')
    op.drop_table('sous_traitant')
    op.drop_table('client_initial')
    op.drop_table('chauffeur')
    # ### end Alembic commands ###
